package model.listener;

public enum EventType {
	APPEARANCE, DISAPPEARANCE ,INITIALIZE, MOVE, START, STOP, KEY_PRESS, KEY_RELEASE, MOVE_UP, MOVE_DOWM, MOVE_LEFT, MOVE_RIGHT, A, UPDATE, COLLISION, GAME_OVER;
}
